### ISSUE TITLE
error when compiling stp from git repository

### ISSUE THREAD

**Issue by dr1861** [stp/stp#171]
I cloned a copy of stp this evening, and after running cmake, I tried to compile the project using:

$ make

I am getting the following error:
/usr/include/minisat/utils/Options.h:285:29: error: unable to find string literal operator â€˜operator"" PRIi64â€™

I am working on debian 7.8 32-bit and have installed minisat and minisat2 from the package repository.
Is there a fix for this problem?

**Comment by delcypher** [comment]
You need to be a bit more descriptive than that

* what compiler are you using?
* Compilation of what part of STP causes the error.
* What is the full error message. You've truncated it.

Did Minisat actually compile for you? I took a look at the the line mentioned in the error you gave and if STP can't use the header properly I would of thought you would have problems building minisat from source.

**Comment by delcypher** [comment]
Actually looks like @msoos found some issues
https://github.com/niklasso/minisat/pull/24

@msoos Is this related?

**Comment by msoos** [comment]
Hey,

From phone, sorry. Yes, very related. Newer compiler would help. Also, you
can fix it by uninstalling MiniSat and installing the version from
stp/MiniSat. It has the fix you need. Ultimately we will need to compile
MiniSat.c without the stdc++11 flag. Will fix soon! (Dan, can you try
fixing it?)

Actually looks like @msoos <https://github.com/msoos> found some issues
niklasso/minisat#24 <https://github.com/niklasso/minisat/pull/24>

@msoos <https://github.com/msoos> Is this related?

—
Reply to this email directly or view it on GitHub
<https://github.com/stp/stp/issues/171#issuecomment-90828994>.

**Comment by msoos** [comment]
Dear @dr1861 ,

Please see if this fixes the problem. I believe it should, but it'd be really good to confirm. Thank you very much for this bug report, it helped me think a bit more about the bug and hopefully fix it in a less intrusive way.

Thanks again,

Mate

**Comment by dr1861** [comment]
Mate,
I pulled a fresh copy fo stp from the git repository this morning and
it built on my debian 7.8 system no problems.
Thanks so much for the fix.

Sincerely,
Donald

**Comment by msoos** [comment]
Thanks for getting back to me and good luck using the system! If you encounter any issue, or have a suggestion, please open an issue! Cheers!
