### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by ccadar** [stp/stp#224]
Hi, first of all I noticed that the TravisCI build is not working anymore, why is that?

The current version of STP fails to build on my Ubuntu 14.04 machine.  I haven't investigated the causes yet, but here is the error message I receive.  I am wondering if this is a known issue.  Thanks!

```
...
Linking CXX executable ../../stp
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libpthread.a(nptl-init.o): In function `__pthread_initialize_minimal_internal':
/build/buildd/eglibc-2.19/nptl/nptl-init.c:285: undefined reference to `__libc_setup_tls'
/build/buildd/eglibc-2.19/nptl/nptl-init.c:303: undefined reference to `_dl_cpuclock_offset'
/build/buildd/eglibc-2.19/nptl/nptl-init.c:419: undefined reference to `_dl_pagesize'
/build/buildd/eglibc-2.19/nptl/nptl-init.c:428: undefined reference to `_dl_pagesize'
/build/buildd/eglibc-2.19/nptl/nptl-init.c:448: undefined reference to `_dl_init_static_tls'
/build/buildd/eglibc-2.19/nptl/nptl-init.c:450: undefined reference to `_dl_wait_lookup_done'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libpthread.a(nptl-init.o): In function `__pthread_get_minstack':
/build/buildd/eglibc-2.19/nptl/nptl-init.c:471: undefined reference to `_dl_pagesize'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libpthread.a(pthread_create.o): In function `allocate_stack':
/build/buildd/eglibc-2.19/nptl/allocatestack.c:475: undefined reference to `_dl_stack_flags'
/build/buildd/eglibc-2.19/nptl/allocatestack.c:614: undefined reference to `_dl_stack_flags'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libpthread.a(pthread_getattr_np.o): In function `pthread_getattr_np':
/build/buildd/eglibc-2.19/nptl/pthread_getattr_np.c:99: undefined reference to `_dl_pagesize'
/build/buildd/eglibc-2.19/nptl/pthread_getattr_np.c:135: undefined reference to `_dl_pagesize'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libpthread.a(pt-vfork.o): In function `__vfork':
/build/buildd/eglibc-2.19/nptl/../sysdeps/unix/sysv/linux/x86_64/64/../../../../../../sysdeps/unix/sysv/linux/x86_64/vfork.S:52: undefined reference to `__syscall_error'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libpthread.a(ptw-write.o): In function `__write_nocancel':
/build/buildd/eglibc-2.19/nptl/../sysdeps/unix/syscall-template.S:81: undefined reference to `__syscall_error'
/build/buildd/eglibc-2.19/nptl/../sysdeps/unix/syscall-template.S:81: undefined reference to `__syscall_error'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libpthread.a(ptw-read.o): In function `__read_nocancel':
/build/buildd/eglibc-2.19/nptl/../sysdeps/unix/syscall-template.S:81: undefined reference to `__syscall_error'
/build/buildd/eglibc-2.19/nptl/../sysdeps/unix/syscall-template.S:81: undefined reference to `__syscall_error'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libpthread.a(ptw-close.o):/build/buildd/eglibc-2.19/nptl/../sysdeps/unix/syscall-template.S:81: more undefined references to `__syscall_error' follow
collect2: error: ld returned 1 exit status
make[2]: *** [stp-2.1.2] Error 1
make[1]: *** [tools/stp/CMakeFiles/stp.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by msoos** [comment]
Hi Cristian,

Forst of all thanks for the detailed report and sorry for the
inconvenience. I'll get back to you tomorrow. Build should work, it was
just a failure of llvm source location and signing key that killed
TravisCI. I'll fix that. I suspect there is an issue with pthread linking,
it should be easy to fix, it works on my Ubuntu 14.04 so fix will ne easy.
Some install/build notes need updating that's all, I think. I'll get back
to you tomorrow! Have a great weekend and thanks again for the report,

Mate

**Comment by n1k55** [comment]
Hello,

I am having the same issue on my Linux Mint 17.3 box. Bisecting shows, that the issue seems to be introduced by [bfd0a639f577937ee3ebfaa1ab5cbda577d76706](https://github.com/stp/stp/commit/bfd0a639f577937ee3ebfaa1ab5cbda577d76706) with [670aee22d916b2ffa260684981d2395e897be8e7](https://github.com/stp/stp/commit/670aee22d916b2ffa260684981d2395e897be8e7) linking fine.

**Comment by andreamattavelli** [comment]
`-lpthread` in [CMakelist.txt:128](https://github.com/stp/stp/blob/master/CMakeLists.txt#L128) is the source of the issue. As far as I understood libc is linked dynamically while pthread statically (or vice versa).

**Comment by msoos** [comment]
Hi All!

I have tested and things should work. Please follow the guide I put into INSTALL.md. The TravisCI should also work from now on (fixed location of PGP key).

The point is that static and binary building have changed. You need a static library. So you need to:

* statically build cryptominisat. This means deleting the "build" directory, then doing "cmake -DSTATICCOMPILE=ON .."

**Comment by msoos** [comment]
(sorry, previous update went haywire). I have fixed&tested and things should now work. Please follow the guide I put into INSTALL.md. The TravisCI is also working, it's green now, building KLEE with STP and CryptoMiniSat4.

The static and binary building have changed. You need a static library for KLEE. So you need to:

* statically build CryptoMiniSat4. This means re-pulling, deleting the "build" directory, re-creating it then doing `cmake -DSTATICCOMPILE=ON ..`

* statically build STP. This means re-pulling, deleting the "build" directory, re-creating it, and then doing `cmake -DBUILD_SHARED_LIBS=OFF ..`

The first produces libcryptominisat4.a and the second will produce libstp.a. KLEE works with these as per TravisCI. Note that I use this setup on an Ubuntu14.04 and it works. I submitted the static binaries (`-DBUILD_STATIC_BIN=ON` needed for STP to build static binary) thus created to the SAT and SMT competition and it worked for them too. Note that we got 2nd place on the SMT competition this year.

**Comment by ccadar** [comment]
Thanks, @msoos !  It works now, and we just need to update the instructions at http://klee.github.io/build-stp/.  Great to have TravisCI back again.

**Comment by Anum-Tahir** [comment]
okay i was reading this thread and i feel like this issue is similar to the one I posted about just a while ago (#345 ). Can anyone please instruct me about how exactly these commands need to be changed on http://klee.github.io/build-stp/.
i am still using the commands given in issue #345 and it gives the undefined reference error. I am new to linux, so can you please guide me about the exact commands which should be run ?

**Comment by rgov** [comment]
Hi @Anum-Tahir this bug is 4 years old, the README in the project has up to date build instructions. If you have trouble with them, could you please file a new issue with more detail? We would need to know: the OS version, the version of STP sources, the commands you ran, and the output of those commands.

**Comment by Anum-Tahir** [comment]
Thank you very much for reaching out @rgov. I read your email regarding it
being a 4 year old issue. I am sorry for being too late on the reply. The
reason for it is that I am now unable to log into my ubuntu. It is just
extremely slow and doesn't boot at all. First, i thought it was some memory
issue (I have installed ubuntu using virtual box within windows). but since
it got installed and worked totally fine earlier, this is probably not
related to the memory. This problem is not related to the thread i started
but it will be much appreciated if you can guide me on this. I have already
tried uninstalling and reinstalling the machine, it worked and got
completely installed but didn't boot again after the restart.

I will look into the README in the project for the latest build
instructions as you directed once I can log in and start using ubuntu
again. I will try that out while building STP and give you feedback weather
i get another (new type of) error. Thank you very much for your help!
